### PR TITLE
fix: audio volume

### PR DESCRIPTION
**Pull request by sammcj**
- Add audio volume control for ES8311

Hopefully allows for a fix for https://github.com/jesserockz/esp32-s3-box-3-board/issues/3

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]

**Comment by DaveBKC** [comment]
It looks as though this fix didn't make it into 2024.4.0, correct? I didn't see it in the changelog and the UI looks the same.

**Comment by janstadt** [comment]
I'd also love to see a volume control in esphome/ha. Is this going to be in the next release?

**Comment by ecto1a2003** [comment]
could the volume be made controllable in HA?

**Comment by DaveBKC** [comment]
Is anyone still looking at this? Is it assumed to be fixed? If it is fixed, can someone share what we need to do to our yaml that hasn't already been covered?

**Comment by genehand** [comment]
Here's what I'm using based on [sammcj's custom component](https://github.com/sammcj/esphome-esp-s3-box-3-volume):

```yaml
external_components:
  - source: github://sammcj/esphome-esp-s3-box-3-volume@main
    components: [esp_box_volume]
    refresh: 30min

esp_box_volume:
  id: speaker_volume

number:
  - name: Volume
    id: volume
    platform: template
    entity_category: config
    min_value: 0
    max_value: 1.0
    step: 0.05
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0.85
    on_value:
      - lambda: id(speaker_volume).set_volume(x);
```

**Pull request merged**
